//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orionik.EnglishTextsTrainer.Views.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orionik.EnglishTextsTrainer.Views.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to База.
        /// </summary>
        public static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити ігнороване.
        /// </summary>
        public static string DeleteIgnore {
            get {
                return ResourceManager.GetString("DeleteIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити те що знаю.
        /// </summary>
        public static string DeleteKnow {
            get {
                return ResourceManager.GetString("DeleteKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Експорт.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ігнорувати.
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to всі.
        /// </summary>
        public static string IsAll {
            get {
                return ResourceManager.GetString("IsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ігноровані.
        /// </summary>
        public static string IsIgnore {
            get {
                return ResourceManager.GetString("IsIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to знаю.
        /// </summary>
        public static string IsKnow {
            get {
                return ResourceManager.GetString("IsKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to неігноровані.
        /// </summary>
        public static string IsNotIgnore {
            get {
                return ResourceManager.GetString("IsNotIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не знаю.
        /// </summary>
        public static string IsNotKnow {
            get {
                return ResourceManager.GetString("IsNotKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to знаю.
        /// </summary>
        public static string Know {
            get {
                return ResourceManager.GetString("Know", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to значення.
        /// </summary>
        public static string Meaning {
            get {
                return ResourceManager.GetString("Meaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відкрити.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Експорт англійських слів.
        /// </summary>
        public static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проект.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти всі невідомі, що є в базі.
        /// </summary>
        public static string SaveAllNotKnow {
            get {
                return ResourceManager.GetString("SaveAllNotKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пропонований переклад.
        /// </summary>
        public static string Translate {
            get {
                return ResourceManager.GetString("Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to слово.
        /// </summary>
        public static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
    }
}
